### ISSUE TITLE
Crash right after "Finding trades..."

### ISSUE THREAD

**Issue by spam8117** [tomreece/pucauto#18] opened 2015-11-23 19:27 UTC
Hello Tom,
I tried Pucauto today, installed everything as told and also installed Firefox (didn't have it before).
Now Pucauto starts, then this happens:

Logging in...
Turning on auto matching...
Sorting by member...
Finding trades...
Traceback (most recent call last):
  File "pucauto.py", line 239, in <module>
    main()
  File "pucauto.py", line 236, in main
    find_trades()
  File "pucauto.py", line 216, in find_trades
    valid_trades = filter_trades_dict(trades)
  File "pucauto.py", line 177, in filter_trades_dict
    for member, v in trades.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

Any ideas? Thank you :)
Pucauto looks very promising!

**Comment by XVicarious** [comment] 2015-11-23 19:36
Use Python 2.  Duplicate of #16

**Comment by spam8117** [comment] 2015-11-23 19:42
Thank you, now it doesn't crash anymore. But it goes ~30 seconds between each site refresh.
Is this working as intended or should it refresh faster (I read something about ~5 seconds).

**Comment by XVicarious** [comment] 2015-11-23 21:00
I'm not the developer, so I'm not sure.  I read through the script and there doesn't seem to be a reason it refreshes every ~30 seconds.  I see about 6 seconds of waits.  Could it be your connection?

**Comment by spam8117** [comment] 2015-11-23 21:18
Let's wait for the developer then :) connection should be fine (around 76 Mbps), maybe it has something to do with the length of the list and/or minimum points value (waiting for all the calculations, I don't know...). I have set a minimum points value of 200.

**Comment by tomreece** [comment] 2015-11-23 21:28
If your Send Cards list is huge, it will take time to parse it all. I didn't realize how many trades some people have on their Haves list. During testing, my Send Cards page only has about 100 to 200 rows. I will work on optimizing this. Thanks for reporting.

**Comment by tomreece** [comment] 2015-11-23 21:29
@spam8117 Can you file a new issue about performance and close this one since your original issue was resolved by switching to Python 2? Include details about how many cards are on your Haves list. That will help.

**Comment by tomreece** [comment] 2015-11-24 01:45
@spam8117 Pucauto used to work much faster when it only accepted one trade at a time because all it had to do was grab the first row in the table on the Send Cards page. Now it has to scroll to the bottom to load everything (due to PucaTrade's implementation), iterate through every row, build a data structure and then accept trades. It's a tradeoff between bundling and speed.

Anyway, I'm going to close this issue for now and continue to monitor performance to see if there is anything I can do to increase it for large trades list.

**Closed as completed by tomreece** 2015-11-24 01:45 UTC
