### ISSUE TITLE
Temp Directory Filled Up

### ISSUE THREAD

**Issue by isutrumpet** [tomreece/pucauto#69] opened 2016-01-15 17:06 UTC
I have noticed on my Win7 VM that my C:\Users[USER]\AppData\Local\Temp directory is being filled with sub-directories called "scoped_dir".  I have so far collected 26GB of these temp files.  After some quick research, I believe it may be related to this issue:

http://stackoverflow.com/questions/18686999/chromedriver-chrome-filling-up-system-temp-folder

I don't see this as a super high priority problem, but wanted to report it anyway.  Keep up the good work!

**Comment by tomreece** [comment] 2016-01-19 03:10
@isutrumpet Thanks for the report. I have noticed this happening on my VM as well. I have to occasionally clear out the /tmp folder.

I'll work on a change soon that either ensures `driver.quit()` is called or ideally find a way to use the same tmp cache for every run of the bot instead of a new one for each run.

**Comment by tomreece** [comment] 2016-02-13 22:09
Closing this. It's a duplicate of #64

**Closed as completed by tomreece** 2016-02-13 22:09 UTC
Labels: rare, bug
